#!/usr/bin/env python3
"""
简单API测试脚本
"""

import requests
import json
import time

BASE_URL = "http://localhost:8000"

def test_health():
    """测试健康检查"""
    print("🏥 测试健康检查...")
    try:
        response = requests.get(f"{BASE_URL}/health", timeout=10)
        if response.status_code == 200:
            data = response.json()
            print(f"✅ 服务正常")
            print(f"   模型已加载: {data['model_loaded']}")
            print(f"   设备: {data['device']}")
            return True
        else:
            print(f"❌ 健康检查失败: {response.status_code}")
            return False
    except Exception as e:
        print(f"❌ 健康检查异常: {e}")
        return False

def test_ask_question():
    """测试问答功能"""
    print("\n💬 测试问答功能...")
    val_dict = {"question":"Chromosome Number: 7\nNetwork Definition of the pathway: EGFR* -> GRB2 -> SOS -> RAS -> RAF -> MEK -> ERK -> CCND1\nGenes in the pathway: EGFR; epidermal growth factor receptor | GRB2; growth factor receptor bound protein 2 | SOS1; SOS Ras\/Rac guanine nucleotide exchange factor 1 | SOS2; SOS Ras\/Rho guanine nucleotide exchange factor 2 | HRAS; HRas proto-oncogene, GTPase | KRAS; KRAS proto-oncogene, GTPase | NRAS; NRAS proto-oncogene, GTPase | ARAF; A-Raf proto-oncogene, serine\/threonine kinase | BRAF; B-Raf proto-oncogene, serine\/threonine kinase | RAF1; Raf-1 proto-oncogene, serine\/threonine kinase | MAP2K1; mitogen-activated protein kinase kinase 1 | MAP2K2; mitogen-activated protein kinase kinase 2 | MAPK1; mitogen-activated protein kinase 1 | MAPK3; mitogen-activated protein kinase 3 | CCND1; cyclin D1\n\nGiven this context, what is the biological effect of this EGFR allele, specifically what disease does this contribute to?","answer":"non-small cell lung cancer","reasoning":"Step 1: The variant is a C>T substitution at position 55181377 on chromosome 7, which corresponds to the EGFR gene.\nStep 2: This specific mutation is likely the well-characterized L858R mutation in exon 21 of EGFR, which results in a leucine to arginine substitution at amino acid position 858.\nStep 3: The L858R mutation occurs in the activation loop of the tyrosine kinase domain of EGFR, altering its conformation.\nStep 4: This conformational change leads to constitutive activation of EGFR's kinase activity, even in the absence of ligand binding.\nStep 5: Constitutively active EGFR leads to persistent phosphorylation of downstream adaptor proteins like GRB2, which recruits SOS proteins.\nStep 6: SOS proteins act as guanine nucleotide exchange factors that activate RAS proteins (HRAS, KRAS, NRAS) by facilitating GDP to GTP exchange.\nStep 7: Activated RAS-GTP then triggers the RAF-MEK-ERK kinase cascade through sequential phosphorylation events.\nStep 8: Activated ERK translocates to the nucleus and phosphorylates transcription factors that upregulate expression of cell cycle regulators like cyclin D1 (CCND1).\nStep 9: Increased cyclin D1 promotes G1 to S phase transition in the cell cycle, driving cellular proliferation.\nStep 10: This hyperactivated EGFR signaling pathway leads to uncontrolled cell growth, survival, and evasion of apoptosis - hallmarks of cancer.\nStep 11: In the lung epithelium, these cellular changes contribute to the development of non-small cell lung cancer (NSCLC), particularly adenocarcinoma.\nStep 12: Importantly, tumors with this EGFR L858R mutation are often sensitive to EGFR tyrosine kinase inhibitors (TKIs) like gefitinib and erlotinib, making it an important biomarker for targeted therapy.\nThis EGFR mutation (likely L858R) causes constitutive activation of the EGFR tyrosine kinase domain, leading to persistent downstream signaling through the RAS-RAF-MEK-ERK pathway that promotes cell proliferation and survival. This mutation is a common driver in non-small cell lung cancer (NSCLC), particularly lung adenocarcinoma, and is associated with sensitivity to EGFR tyrosine kinase inhibitors.","reference_sequence":"CTGCTTTCTGAAGGAAAAACTGCAAGATACCAGGAGAGTTTCATTTAGATTGAAGAGTCGAGGAAGGCTCCTCTGAGAAAGAGTCTGCTAAGGAAGGAGGAGGTGGGTTCTGGGGACAGAGGTTCTCCCGTGGGTAAGGGTGGAGGGAAGCTCTCCTGGGGAGAAGGTGGGCAGGAGGACCAGAGGCTGGAGGGAGGAGGGCAGTCAGCCTCGGGGCTTCCCAGGAACAGGGACGGCCAGGGCAGGGTTTAGGGCAAGGAAAGCGTGTGAGCATATTTGTATTTTAGTAAATATTTACAGTTTGCCCTCCATGTCTGCAGTTTCATATCCATGGATTCAATCAACCACAATGAAAAACGTTGGGGAAAAAAATTGCATCGGTACTGAACATATACGGACTTTTTTTCTTGTCATTATTCCCTAAACAATACAGCATAACAATTATTCACATAGCATTTGCACTGTATTAGGTACTATAGGTAATCAGGAGATGCTGTAGATGGGAGGATGTCTGTAGGTTACACACAAATGCTGTGCCACTTTATATCAGGGGCTTGAGCATCCTCACATTTTGATATTTAAGGGAGGTCCTGGAACCAATTCCCCAGATACTGAGGGTCCACTGTCTGTGTCCCCTCGCCCCACCTTGCCTTTGTCTCCTGTCTCCTATCTCCACCCTGCCTCCCGCCAGCCTGTTGCTCCTGACCTGCCCGGGCACCCTGGAGCAGCACCCTATCTCAGAGCCTGGCTCAGTGTGTTCACTTCTGCAGAGAAACTAACTTGCCCAAGTCCACACTCAAAACATAGGCATTGCTGAGATGTGAAAAGCAGCTGTGGATGCTTTCTGCTACAGTCTGTGTGTTCTTTTCCATATCTGAATAAAAGGTCACCACCATTTGTATTTTAAAGAGAAAGAGAATTTATGGGTGGAAATTGGGGATTCCCTCATTCTCAGTCAGACAGAAAAGAGGGCCCCATTGTGTGCCTGATTGCAAATAAATTTAGCTTCCTCAGCCCAAGAATAGCAGAAGGGTTAAAATAAAGTCTGTATTTATGGCTCTGTCAAAGGAAGGCCCCTGCCTTGGCAGCCAGCCGGAATTAGCAGGGCAGCAGATGCCTGACTCAGTGCAGCATGGATTTCCCATAGGGAGCCTGGGGGCACAGCACAGAGAGACCACTTCTCTTTAGAAATGGGTCCCGGGCAGCCAGGCAGCCTTTAGTCACTGTAGATTGAATGCTCTGTCCATTTCAAAACCTGGGACTGGTCTATTGAAAGAGCTTATCCAGCTACTCTTTGCAGAGGTGCTGTGGGCAGGGTCCCCAGCCCAAATGCCCACCCATTTCCCAGAGCACAGTCAGGGCCAAGCCTGGCCTGTGGGGAAGGGAGGCCTTTCTCCCTGCTGGCTCGGTGCTCCCCGGATGCCTTCTCCATCGCTTGTCCTCTGCAGCACCCACAGCCAGCGTTCCTGATGTGCAGGGTCAGTCATTACCCAGGGTGTTCCGGACCCCACACAGATTCCTACAGGCCCTCATGATATTTTAAAACACAGCATCCTCAACCTTGAGGCGGAGGTCTTCATAACAAAGATACTATCAGTTCCCAAACTCAGAGATCAGGTGACTCCGACTCCTCCTTTATCCAATGTGCTCCTCATGGCCACTGTTGCCTGGGCCTCTCTGTCATGGGGAATCCCCAGATGCACCCAGGAGGGGCCCTCTCCCACTGCATCTGTCACTTCACAGCCCTGCGTAAACGTCCCTGTGCTAGGTCTTTTGCAGGCACAGCTTTTCCTCCATGAGTACGTATTTTGAAACTCAAGATCGCATTCATGCGTCTTCACCTGGAAGGGGTCCATGTGCCCCTCCTTCTGGCCACCATGCGAAGCCACACTGACGTGCCTCTCCCTCCCTCCAGGAAGCCTACGTGATGGCCAGCGTGGACAACCCCCACGTGTGCCGCCTGCTGGGCATCTGCCTCACCTCCACCGTGCAGCTCATCACGCAGCTCATGCCCTTCGGCTGCCTCCTGGACTATGTCCGGGAACACAAAGACAATATTGGCTCCCAGTACCTGCTCAACTGGTGTGTGCAGATCGCAAAGGTAATCAGGGAAGGGAGATACGGGGAGGGGAGATAAGGAGCCAGGATCCTCACATGCGGTCTGCGCTCCTGGGATAGCAAGAGTTTGCCATGGGGATATGTGTGTGCGTGCATGCAGCACACACACATTCCTTTATTTTGGATTCAATCAAGTTGATCTTCTTGTGCACAAATCAGTGCCTGTCCCATCTGCATGTGGAAACTCTCATCAATCAGCTACCTTTGAAGAATTTTCTCTTTATTGAGTGCTCAGTGTGGTCTGATGTCTCTGTTCTTATTTCTCTGGAATTCTTTGTGAATACTGTGGTGATTTGTAGTGGAGAAGGAATATTGCTTCCCCCATTCAGGACTTGATAACAAGGTAAGCAAGCCAGGCCAAGGCCAGGAGGACCCAGGTGATAGTGGTGGAGTGGAGCAGGTGCCTTGCAGGAGGCCCAGTGAGGAGGTGCAAGGAGCTGACAGAGGGCGCAGCTGCTGCTGCTATGTGGCTGGGGCCTTGGCTAAGTGTCCCCCTTTCCACAGGCTCGCTCCAGAGCCAGGGCGGGGCTGAGAGAGCAGAGTGGTCAGGTAGCCCTGCCTGGGTGCTGGAGACAGGCACAGAACAACAAGCCAGGTATTTCACAGCTGGTGCGGACCCAGAAAGACTTCTGCTTTTGCCCCAAACCCCTCCCATCTCCATCCCAGTCTTGCATCAGTTATTTGCACTCAACTTGCTAAGTCCTATTTTTTTCTAACAATGGGTATACATTTCATCCCATTGACTTTAAAGGATTTGCAGGCAGGCCCTGTCTCTGAGAATACGCCGTTGCCCGTCATCTCTCTCCGACAGCAGGGCAGGGGGTCCAGAGATGTGCCAGGGACCAGAGGGAGGGAGCAGACACCCACCCGGCCTGGGCAGGTCCTCCTCATTGCTTGCATCCGCCTGGTTAGCAGTGGCAGTCAGTCCTGCCGAGTCATTCGTGAGGCGCTCACCCAACTCCAGGCAGATGTAAAAGGTGACCTACAAGAAGACAAACAAAAACATCTGGAGCGCTCTTATGCCAGCATCTGCCCTTGACACCACCAGGCAGGCTGTTGCTGGGAGCCGTGGTGCTTGGGTAAGCTCCTTCCCATGGCAGAGCTCCTGGGACGCATTGTAGAAGCAGGGACCACCTCCCAGGATAACCAGATAGCAGCACACCCTGCACAGCCCCTTTTACTCCAGCATCATCGGGCATTGATATCTCAGCTGCAGCCACAGGCGGCCCCCAGCACCCCAGGAAGTGGGGAGCGCTCATGCTTCTCTGAGCACAAAAATCACTGAATATTTTTGCCATTCTCATGGTCATAACCCGGGCCACAGAGTAGAACACTCCTATCACTGTTGTTAGACAGTGGTCCTGGGAGAGGGTCTTGTGTGCCTCGGATGCCAGGGCCTCTTTTTATTGGGAGGTGCTTGTTATTTCTGTGTGTGGCTGCATTTGTTTCCCAAGACTGCCACAACAAATCATCACCAACTTGGTAGCTCAACATAGCACAGCTTTATTCCCTCCTGGCTCTGGAGGCCAGGTGTCTAAAAGGCCATGCTCCCACAATGGTTCTGAGGAGGATCCTTCCTGCCTCTCTGGCTTCTGGTGGCTCCAGCATCCCTGGGCTGTGGCTGCACCTCCCCATGTCAACCTCCGTCTTCACAAGGCCTTTTCCTGTGTCTCTGCAACCACAGGCCCCTCTCCTTTCTCTTAATAAAGATACCAGTCATTGAGTTTGAAAATTGCTAAGAGAGTCTGTTGTAAATCTTCTTAGCACAAAAAAAAATGACAGATATGTGAAGTGGTAGATATATTAATTAGTTTGATTTGATCACTCCGCTATGTGTATAAATGTCAAAACAAACATTGCACTCCATAAATATATATATTAAA","variant_sequence":"CTGCTTTCTGAAGGAAAAACTGCAAGATACCAGGAGAGTTTCATTTAGATTGAAGAGTCGAGGAAGGCTCCTCTGAGAAAGAGTCTGCTAAGGAAGGAGGAGGTGGGTTCTGGGGACAGAGGTTCTCCCGTGGGTAAGGGTGGAGGGAAGCTCTCCTGGGGAGAAGGTGGGCAGGAGGACCAGAGGCTGGAGGGAGGAGGGCAGTCAGCCTCGGGGCTTCCCAGGAACAGGGACGGCCAGGGCAGGGTTTAGGGCAAGGAAAGCGTGTGAGCATATTTGTATTTTAGTAAATATTTACAGTTTGCCCTCCATGTCTGCAGTTTCATATCCATGGATTCAATCAACCACAATGAAAAACGTTGGGGAAAAAAATTGCATCGGTACTGAACATATACGGACTTTTTTTCTTGTCATTATTCCCTAAACAATACAGCATAACAATTATTCACATAGCATTTGCACTGTATTAGGTACTATAGGTAATCAGGAGATGCTGTAGATGGGAGGATGTCTGTAGGTTACACACAAATGCTGTGCCACTTTATATCAGGGGCTTGAGCATCCTCACATTTTGATATTTAAGGGAGGTCCTGGAACCAATTCCCCAGATACTGAGGGTCCACTGTCTGTGTCCCCTCGCCCCACCTTGCCTTTGTCTCCTGTCTCCTATCTCCACCCTGCCTCCCGCCAGCCTGTTGCTCCTGACCTGCCCGGGCACCCTGGAGCAGCACCCTATCTCAGAGCCTGGCTCAGTGTGTTCACTTCTGCAGAGAAACTAACTTGCCCAAGTCCACACTCAAAACATAGGCATTGCTGAGATGTGAAAAGCAGCTGTGGATGCTTTCTGCTACAGTCTGTGTGTTCTTTTCCATATCTGAATAAAAGGTCACCACCATTTGTATTTTAAAGAGAAAGAGAATTTATGGGTGGAAATTGGGGATTCCCTCATTCTCAGTCAGACAGAAAAGAGGGCCCCATTGTGTGCCTGATTGCAAATAAATTTAGCTTCCTCAGCCCAAGAATAGCAGAAGGGTTAAAATAAAGTCTGTATTTATGGCTCTGTCAAAGGAAGGCCCCTGCCTTGGCAGCCAGCCGGAATTAGCAGGGCAGCAGATGCCTGACTCAGTGCAGCATGGATTTCCCATAGGGAGCCTGGGGGCACAGCACAGAGAGACCACTTCTCTTTAGAAATGGGTCCCGGGCAGCCAGGCAGCCTTTAGTCACTGTAGATTGAATGCTCTGTCCATTTCAAAACCTGGGACTGGTCTATTGAAAGAGCTTATCCAGCTACTCTTTGCAGAGGTGCTGTGGGCAGGGTCCCCAGCCCAAATGCCCACCCATTTCCCAGAGCACAGTCAGGGCCAAGCCTGGCCTGTGGGGAAGGGAGGCCTTTCTCCCTGCTGGCTCGGTGCTCCCCGGATGCCTTCTCCATCGCTTGTCCTCTGCAGCACCCACAGCCAGCGTTCCTGATGTGCAGGGTCAGTCATTACCCAGGGTGTTCCGGACCCCACACAGATTCCTACAGGCCCTCATGATATTTTAAAACACAGCATCCTCAACCTTGAGGCGGAGGTCTTCATAACAAAGATACTATCAGTTCCCAAACTCAGAGATCAGGTGACTCCGACTCCTCCTTTATCCAATGTGCTCCTCATGGCCACTGTTGCCTGGGCCTCTCTGTCATGGGGAATCCCCAGATGCACCCAGGAGGGGCCCTCTCCCACTGCATCTGTCACTTCACAGCCCTGCGTAAACGTCCCTGTGCTAGGTCTTTTGCAGGCACAGCTTTTCCTCCATGAGTACGTATTTTGAAACTCAAGATCGCATTCATGCGTCTTCACCTGGAAGGGGTCCATGTGCCCCTCCTTCTGGCCACCATGCGAAGCCACACTGACGTGCCTCTCCCTCCCTCCAGGAAGCCTACGTGATGGCCAGCGTGGACAACCCCCACGTGTGCCGCCTGCTGGGCATCTGCCTCACCTCCACCGTGCAGCTCATCATGCAGCTCATGCCCTTCGGCTGCCTCCTGGACTATGTCCGGGAACACAAAGACAATATTGGCTCCCAGTACCTGCTCAACTGGTGTGTGCAGATCGCAAAGGTAATCAGGGAAGGGAGATACGGGGAGGGGAGATAAGGAGCCAGGATCCTCACATGCGGTCTGCGCTCCTGGGATAGCAAGAGTTTGCCATGGGGATATGTGTGTGCGTGCATGCAGCACACACACATTCCTTTATTTTGGATTCAATCAAGTTGATCTTCTTGTGCACAAATCAGTGCCTGTCCCATCTGCATGTGGAAACTCTCATCAATCAGCTACCTTTGAAGAATTTTCTCTTTATTGAGTGCTCAGTGTGGTCTGATGTCTCTGTTCTTATTTCTCTGGAATTCTTTGTGAATACTGTGGTGATTTGTAGTGGAGAAGGAATATTGCTTCCCCCATTCAGGACTTGATAACAAGGTAAGCAAGCCAGGCCAAGGCCAGGAGGACCCAGGTGATAGTGGTGGAGTGGAGCAGGTGCCTTGCAGGAGGCCCAGTGAGGAGGTGCAAGGAGCTGACAGAGGGCGCAGCTGCTGCTGCTATGTGGCTGGGGCCTTGGCTAAGTGTCCCCCTTTCCACAGGCTCGCTCCAGAGCCAGGGCGGGGCTGAGAGAGCAGAGTGGTCAGGTAGCCCTGCCTGGGTGCTGGAGACAGGCACAGAACAACAAGCCAGGTATTTCACAGCTGGTGCGGACCCAGAAAGACTTCTGCTTTTGCCCCAAACCCCTCCCATCTCCATCCCAGTCTTGCATCAGTTATTTGCACTCAACTTGCTAAGTCCTATTTTTTTCTAACAATGGGTATACATTTCATCCCATTGACTTTAAAGGATTTGCAGGCAGGCCCTGTCTCTGAGAATACGCCGTTGCCCGTCATCTCTCTCCGACAGCAGGGCAGGGGGTCCAGAGATGTGCCAGGGACCAGAGGGAGGGAGCAGACACCCACCCGGCCTGGGCAGGTCCTCCTCATTGCTTGCATCCGCCTGGTTAGCAGTGGCAGTCAGTCCTGCCGAGTCATTCGTGAGGCGCTCACCCAACTCCAGGCAGATGTAAAAGGTGACCTACAAGAAGACAAACAAAAACATCTGGAGCGCTCTTATGCCAGCATCTGCCCTTGACACCACCAGGCAGGCTGTTGCTGGGAGCCGTGGTGCTTGGGTAAGCTCCTTCCCATGGCAGAGCTCCTGGGACGCATTGTAGAAGCAGGGACCACCTCCCAGGATAACCAGATAGCAGCACACCCTGCACAGCCCCTTTTACTCCAGCATCATCGGGCATTGATATCTCAGCTGCAGCCACAGGCGGCCCCCAGCACCCCAGGAAGTGGGGAGCGCTCATGCTTCTCTGAGCACAAAAATCACTGAATATTTTTGCCATTCTCATGGTCATAACCCGGGCCACAGAGTAGAACACTCCTATCACTGTTGTTAGACAGTGGTCCTGGGAGAGGGTCTTGTGTGCCTCGGATGCCAGGGCCTCTTTTTATTGGGAGGTGCTTGTTATTTCTGTGTGTGGCTGCATTTGTTTCCCAAGACTGCCACAACAAATCATCACCAACTTGGTAGCTCAACATAGCACAGCTTTATTCCCTCCTGGCTCTGGAGGCCAGGTGTCTAAAAGGCCATGCTCCCACAATGGTTCTGAGGAGGATCCTTCCTGCCTCTCTGGCTTCTGGTGGCTCCAGCATCCCTGGGCTGTGGCTGCACCTCCCCATGTCAACCTCCGTCTTCACAAGGCCTTTTCCTGTGTCTCTGCAACCACAGGCCCCTCTCCTTTCTCTTAATAAAGATACCAGTCATTGAGTTTGAAAATTGCTAAGAGAGTCTGTTGTAAATCTTCTTAGCACAAAAAAAAATGACAGATATGTGAAGTGGTAGATATATTAATTAGTTTGATTTGATCACTCCGCTATGTGTATAAATGTCAAAACAAACATTGCACTCCATAAATATATATATTAAA"}

    # 准备测试数据
    test_data = {
        "reference_sequence": val_dict['reference_sequence'],
        "variant_sequence": val_dict['variant_sequence'],
        "question": val_dict['question'],
        "max_length": 256,
        "temperature": 0.7
    }
    
    try:
        print("发送请求...")
        response = requests.post(
            f"{BASE_URL}/ask",
            json=test_data,
            timeout=120  # 增加超时时间
        )
        
        if response.status_code == 200:
            data = response.json()
            print(f"\n✅ 问答成功！")
            print(f"\n问题: {test_data['question']}")
            print(f"\n回答:\n{data['answer']}")
            print(f"\n处理时间: {data['processing_time']:.2f}秒")
            return True
        else:
            print(f"❌ 问答失败: {response.status_code}")
            print(f"   错误信息: {response.text}")
            return False
            
    except Exception as e:
        print(f"❌ 问答异常: {e}")
        return False

def main():
    """主测试函数"""
    print("🚀 开始测试简单API服务...")
    print("=" * 60)
    
    # 等待服务启动
    print("⏳ 等待服务启动...")
    time.sleep(5)
    
    # 测试健康检查
    health_ok = test_health()
    
    if not health_ok:
        print("\n❌ 服务未就绪，请先启动服务")
        print("   启动命令: python simple_app.py")
        return False
    
    # 测试问答
    ask_ok = test_ask_question()
    
    # 输出结果
    print("\n" + "=" * 60)
    print("📊 测试结果:")
    print(f"   健康检查: {'✅ 通过' if health_ok else '❌ 失败'}")
    print(f"   问答功能: {'✅ 通过' if ask_ok else '❌ 失败'}")
    
    if health_ok and ask_ok:
        print("\n🎉 所有测试通过！")
        print("\n使用示例:")
        print(f"""
curl -X POST "{BASE_URL}/ask" \\
     -H "Content-Type: application/json" \\
     -d '{{
       "reference_sequence": "ATCGATCGATCG...",
       "variant_sequence": "ATCGATCGATCG...",
       "question": "这个变异的影响是什么？"
     }}'
        """)
    else:
        print("\n⚠️  部分测试失败，请检查日志")
    
    return health_ok and ask_ok

if __name__ == "__main__":
    import sys
    success = main()
    sys.exit(0 if success else 1)
